"""The three seams that decouple the whole system. DO NOT edit this file alone.

Why this file exists:
    The data source must be swappable (sim -> file -> live) by changing one line, and the
    rest of the system must not care which one is active. That only works if everything is
    coded against fixed interfaces. This file *is* those interfaces. Changing a signature
    here ripples everywhere, so it is done deliberately.

The three seams (see docs/02_architecture.md):
    1. Source          — where 12-channel windows come from.
    2. FidelityScorer  — turns a window into one number in [0, 1].
    3. Frame           — the JSON message the server streams to the browser.

Array-shape vocabulary used throughout NeuroLoop:
    X_window : (n_channels, n_times)            one 2-second window of EEG
    X_epochs : (n_epochs, n_channels, n_times)  a stack of windows (calibration/training)
    C        : (n_channels, n_channels)         a covariance matrix
"""

from __future__ import annotations

import dataclasses
import json
from typing import Iterator, Protocol, runtime_checkable

import numpy as np


# --------------------------------------------------------------------------- #
# Seam 1: Source — where samples come from.
# --------------------------------------------------------------------------- #
@runtime_checkable
class Source(Protocol):
    """Anything that can produce EEG windows for NeuroLoop.

    Implementations (src/sources.py): SimSource, FileSource, LiveSource.
    They are interchangeable: server.py holds a `Source` and never knows which one.

    A `Protocol` means "any object with these methods counts as a Source" — we don't
    have to inherit from it, we just have to match the shape. That is what keeps the
    sim/file/live swap to a single line.
    """

    #: Sampling rate of the windows this source yields, in Hz. Differs between the
    #: 160 Hz PhysioNet files and the faster live eego, so downstream code reads it
    #: from here rather than hard-coding 160.
    fs: float

    def calibration_windows(self) -> tuple[np.ndarray, np.ndarray]:
        """Return the two labelled stacks used to build the personal templates.

        Returns:
            X_exec : (n_epochs, n_channels, n_times) — windows where the person was
                     genuinely moving / attempting to move (the movement template).
            X_rest : (n_epochs, n_channels, n_times) — windows where the person rested.
        """
        ...

    def stream(self) -> Iterator[np.ndarray]:
        """Yield live/replayed windows one at a time, forever (or until the file ends).

        Yields:
            X_window : (n_channels, n_times) — the newest 2-second window to be scored.
        """
        ...


# --------------------------------------------------------------------------- #
# Seam 2: FidelityScorer — the original contribution (see docs/04).
# --------------------------------------------------------------------------- #
@runtime_checkable
class FidelityScorer(Protocol):
    """Turns a window into a fidelity value in [0, 1]: how much it looks like *your*
    movement pattern vs *your* rest pattern.

    Two-step lifecycle:
        calibrate(X_exec, X_rest)  -> learn this person's templates (call once per session)
        score(X_window)            -> a number in [0, 1] for each new window
    """

    def calibrate(self, X_exec: np.ndarray, X_rest: np.ndarray) -> None:
        """Learn the personal movement and rest covariance templates.

        Args:
            X_exec : (n_epochs, n_channels, n_times) movement/attempt windows.
            X_rest : (n_epochs, n_channels, n_times) rest windows.
        """
        ...

    def score(self, X_window: np.ndarray) -> float:
        """Score one window.

        Args:
            X_window : (n_channels, n_times)
        Returns:
            fidelity in [0, 1]: ~1 engaged, ~0.5 ambiguous, ~0 resting.
        """
        ...


# --------------------------------------------------------------------------- #
# Seam 3: Frame — what the server streams to the browser, 20x per second.
# --------------------------------------------------------------------------- #
@dataclasses.dataclass
class Frame:
    """One message on the wire (server.py -> ui/). Serialized to JSON.

    The split between `fidelity` and `activation` is deliberate:
        - `fidelity`   is the raw, unsmoothed truth -> drives the honest METER/BAR.
        - `activation` is the smoothed value (EMA)  -> drives the HAND, so it looks
          fluid on a projector. The browser then interpolates toward `activation`
          at 60 fps; it must never drive the mesh straight from the 20 Hz socket.
    """

    t: float                    # timestamp in seconds since stream start
    fidelity: float             # 0..1 raw   -> the meter/bar
    activation: float           # 0..1 smoothed -> the hand
    state: str = "rest"         # "engaged" | "ambiguous" | "rest" (UI label)
    condition: str = ""         # active demo condition (squeeze/imagine/...) or ""
    signal_ok: bool = True      # electrode/signal-quality gate; False -> grey out hand
    coaching: str = ""          # closed-loop instruction shown to the user (R4)
    d_exec: float = 0.0         # distance to movement template (debug/overlay)
    d_rest: float = 0.0         # distance to rest template (debug/overlay)

    def to_json(self) -> str:
        """Serialize to a compact JSON string for the WebSocket."""
        return json.dumps(dataclasses.asdict(self))

    @staticmethod
    def from_json(s: str) -> "Frame":
        """Rebuild a Frame from JSON (used in tests to prove a clean round-trip)."""
        return Frame(**json.loads(s))
